Feature/REP-60193 reduce logs level for auth details
reporty/janus-gateway pull request #88
Opened 2023-02-06 13:56 UTC by Oleksandr0xB

2023-02-06 15:05 UTC, eran-braun requested changes

2023-02-06 15:05 UTC, eran-braun commented on plugins/janus_videoroom.c
> +	JANUS_LOG(LOG_VERB, "janus_videoroom: auth: auth_secret:%s \n", auth_secret);
Align the spaces

2023-02-07 12:10 UTC, Oleksandr0xB commented on plugins/janus_videoroom.c
> +	JANUS_LOG(LOG_VERB, "janus_videoroom: auth: auth_secret:%s \n", auth_secret);
Done

2023-02-08 01:32 UTC, eran-braun approved these changes

2023-02-12 12:09 UTC, merged